[google-photos]
type = google photos
token = {"access_token":"ya29.A0ARrdaM83W_feFNB1LOPgrZ3739EaP_rfDXh3zo770ARpM97R6_SZySPvYXfRZAunpZVuec2E--AmLjf95P3MC9VH8zZMbNCxJKa0BDj7T6vsNkEa5NV6kA1NV_kk2abFTkheioC6Y-IgXZmZNvL-9P_mm4d0Brg","token_type":"Bearer","refresh_token":"1//03j8shpGhiqzpCgYIARAAGAMSNwF-L9Ir3AlPpTXiUNIV7MXQofsFbJmDbVInzWDkIXIqxuD4bmlPgy5qRLuq2TOTR78M1IH4mJ8","expiry":"2022-03-18T13:32:38.393376451+05:00"}

