[google-photos]
type = google photos
token = {"access_token":"ya29.A0ARrdaM8-OLLQS6vbVMQaP-pJHEZvnkhB0ka6JS2Jjoqk8jgMwAu7SwBem7M96ViSWCdou32AYQEtPrqnq790BUN8h0ssCxRvmIdJFasecNa_KGPyNN_9327JkvKObt3MLw6_IjdFDNypYTNuE7G-KEaa3xCkobQ","token_type":"Bearer","refresh_token":"1//03j8shpGhiqzpCgYIARAAGAMSNwF-L9Ir3AlPpTXiUNIV7MXQofsFbJmDbVInzWDkIXIqxuD4bmlPgy5qRLuq2TOTR78M1IH4mJ8","expiry":"2022-03-27T15:31:33.402230055+05:00"}

