[google-photos]
type = google photos
token = {"access_token":"ya29.A0ARrdaM_RMwfVFAOdmm2TP0QBtu70s1ACjXLBr4aGKInWcKRk6kp6SgJnY7t03H0LKwAvXdjjj24UOWLP4eyUceGzDYrUmsG9l1YLjdaBjr5DgfJgLo8pMR-Xcpdt47V-mjCGpMAsOFfk0UhrnzqWyTcAbeAdZXg","token_type":"Bearer","refresh_token":"1//03j8shpGhiqzpCgYIARAAGAMSNwF-L9Ir3AlPpTXiUNIV7MXQofsFbJmDbVInzWDkIXIqxuD4bmlPgy5qRLuq2TOTR78M1IH4mJ8","expiry":"2022-04-24T19:44:43.108668207+05:00"}

